language: android
os: linux
sudo: required

jdk:
 - oraclejdk8


############
# build set-up for android
android:
  components:
    - tools
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-22

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


before_install:


env:
  global:
  - TERM=dumb
  - ANDROID_NDK_HOME=./android-ndk

